// Generated by CoffeeScript 1.3.3
(function() {
  var app, inspect, options, wfl;

  wfl = require('./lib/wfl');

  inspect = require('eyes').inspector();

  options = {
    domain: "wfl-dev-2",
    force: true
  };

  app = wfl(options);

  app.useActivity("hello", function(request, response) {
    return response.send("Hello");
  });

  app.useActivity("world", function(request, response) {
    return response.send(request.input + ", World!");
  });

  app.makeDecision("/start", function(request, response) {
    inspect(request, "Request");
    return response.scheduleActivity("hello", "my name");
  });

  app.makeDecision("/start/hello", function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return app.logger.debug("activity hello status: " + request.task.status);
      case "TIMED_OUT":
        app.logger.debug("activity hello timed out, cancelling the workflow");
        return response.cancel("activity hello timed out");
      case "COMPLETED":
        app.logger.debug("activity hello completed");
        if (request.success) {
          return response.scheduleActivity("world");
        }
        break;
      default:
        return response.cancel();
    }
  });

  app.logger.info("Starting application");

  app.listen();

  setInterval(function() {
    return app.start({
      name: "toto",
      filePath: "/dev/null"
    });
  }, 25000);

}).call(this);
