// Generated by CoffeeScript 1.3.3
(function() {
  var app, inspect, options, wfl;

  wfl = require('./lib/wfl');

  inspect = require('eyes').inspector();

  options = {
    domain: "wfl-dev-2",
    accessKeyId: "AKI4DEDPTQ",
    secretAccessKey: "/YBzjQIEEMum0ZxVOj6jIVCS",
    force: true
  };

  app = wfl(options);

  app.useActivity("hello", function(request, response) {
    return response.send("Hello");
  });

  app.useActivity("world", function(request, response) {
    return response.send(request.input + ", World!");
  });

  app.makeDecision("/start", function(request, response) {
    inspect(request, "Request");
    return response.scheduleActivity("hello");
  });

  app.makeDecision("/start/hello", function(request, response) {
    if (req.success) {
      response.scheduleActivity("world");
    }
    if (request.failed) {
      return response.cancel();
    }
  });

  app.logger.info("Starting application");

  app.listen();

  setInterval(function() {
    return app.start({
      name: "toto",
      filePath: "/dev/null"
    });
  }, 5000);

}).call(this);
