// Generated by CoffeeScript 1.3.3

/* 
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {

  module.exports.videoChecked = function(request, response) {
    switch (request.task.status) {
      case "TIMED_OUT":
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        if (request.task.result.status === "OK") {
          if (request.task.result.size > 50 * 1024 * 1024) {
            return response.scheduleActivity("shortenVideo", request.input);
          } else {
            return response.scheduleActivity("catCheck", request.input);
          }
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error: " + request.task.result.error.code + " - " + request.task.result.error.message);
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  };

  module.exports.videoShortened = function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return response.wait();
      case "TIMED_OUT":
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        if (request.task.result.status === "OK") {
          return response.scheduleActivity("catCheck", {
            url: request.input.url
          });
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error...");
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  };

  module.exports.catChecked = function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return response.wait();
      case "TIMED_OUT":
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        if (request.task.result.status === "OK") {
          if (request.task.result.cats === true) {
            return response.scheduleActivity("rejectVideo", {
              url: request.input.url
            });
          } else {
            return response.scheduleActivity("transcodeVideo", {
              url: request.input.url
            });
          }
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error...");
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  };

  module.exports.videoTranscoded = function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return response.wait();
      case "TIMED_OUT":
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        if (request.task.result.status === "OK") {
          return response.scheduleActivity("publishVideo", {
            url: request.input.url
          });
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error...");
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  };

  module.exports.videoPublished = function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return response.wait();
      case "TIMED_OUT":
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        if (request.task.result.status === "OK") {
          return response.end({
            status: "OK",
            message: "Video Published, workflow successfully completed!"
          });
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error...");
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  };

}).call(this);
