// Generated by CoffeeScript 1.3.3
(function() {
  var app, inspect, options, wfl;

  wfl = require('../../lib/wfl');

  inspect = require('eyes').inspector();

  options = {
    domain: "demos",
    name: "transcoder"
  };

  app = wfl(options);

  app.useActivity("checkVideo", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Checking video: " + request.input.url);
    return response.send({
      status: "OK",
      message: "Found Video in S3",
      size: 1257
    });
  });

  app.useActivity("shortenVideo", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Shortening video: " + request.input.url);
    return response.send({
      status: "OK",
      message: "Video Shortened successfully"
    });
  });

  app.useActivity("catCheck", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Checking video: " + request.input.url + " for cats");
    return response.send({
      status: "OK",
      message: "Clean Video"
    });
  });

  app.useActivity("rejectVideo", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Rejected video: " + request.input.url + ". sending email to the user");
    return response.send({
      status: "OK",
      message: "Video Rejected"
    });
  });

  app.useActivity("transcodeVideo", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Transcoding video: " + request.input.url + ".");
    return response.send({
      status: "OK",
      message: "Transcoded to format H264/AAC"
    });
  });

  app.useActivity("publishVideo", function(request, response) {
    app.logger.verbose("" + request.task.id + " - Publishing video: " + request.input.url + ". sending email to the user");
    return response.send({
      status: "OK",
      message: "Video Published"
    });
  });

  app.makeDecision("/start", function(request, response) {
    app.logger.verbose("Starting Workflow....");
    return response.scheduleActivity("checkVideo", {
      url: request.input.url
    });
  });

  app.makeDecision("/start/checkVideo", function(request, response) {
    app.logger.verbose("Activity " + request.task.id + " responded with the following status: " + request.task.status);
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return response.wait();
      case "TIMED_OUT":
        app.logger.verbose("Activity " + request.task.id + " timed out, cancelling the workflow");
        return response.cancel("Activity " + request.task.id + " timed out");
      case "COMPLETED":
        app.logger.verbose("Activity " + request.task.id + " completed, checking result...");
        if (request.task.result.status === "OK") {
          if (request.task.result.size > 128) {
            app.logger.verbose("Sceduling activity shortenVideo");
            return response.scheduleActivity("shortenVideo", {
              url: request.input.url
            });
          } else {
            app.logger.verbose("Sceduling activity catCheck");
            return response.scheduleActivity("catCheck", {
              url: request.input.url
            });
          }
        } else {
          return response.cancel("Activity " + request.task.id + " responded in error...");
        }
        break;
      default:
        return response.cancel("Activity " + request.task.id + " ended with an unknown status of " + request.task.status + "... cancelling");
    }
  });

  app.makeDecision("/start/hello/world", function(request, response) {
    switch (request.task.status) {
      case "SCHEDULED":
      case "STARTED":
        return app.logger.debug("activity world status: " + request.task.status);
      case "TIMED_OUT":
        app.logger.debug("activity world timed out, cancelling the workflow");
        return response.cancel("activity world timed out");
      case "COMPLETED":
        app.logger.debug("activity world completed with the following result: " + request.task.result + " ");
        return response.end(request.task.result);
      default:
        return response.cancel("unknown status detected... cancelling");
    }
  });

  app.logger.info("Starting application");

  app.listen();

}).call(this);
