// Generated by CoffeeScript 1.3.3
(function() {
  var Activity, ActivityTask, Swf, amazon, awssum, inspect;

  inspect = require('eyes').inspector();

  awssum = require('awssum');

  amazon = awssum.load('amazon/amazon');

  Swf = awssum.load('amazon/swf').Swf;

  ActivityTask = require('./ActivityTask').ActivityTask;

  Activity = (function() {

    function Activity(config, workerFn) {
      var swfCfg,
        _this = this;
      this.config = config;
      this.workerFn = workerFn;
      this.continuePolling = true;
      swfCfg = {
        'accessKeyId': this.config.accessKeyId,
        'secretAccessKey': this.config.secretAccessKey,
        'region': this.config.region
      };
      this.swf = new Swf(swfCfg);
      process.nextTick(function() {
        return _this.poll();
      });
    }

    Activity.prototype.stop = function() {
      return this.continuePolling = false;
    };

    Activity.prototype.poll = function() {
      var swfCfg,
        _this = this;
      if (!this.continuePolling) {
        return;
      }
      console.log("Polling for next activity task...");
      swfCfg = {
        'Domain': this.config.domain,
        'TaskList': this.config.taskList
      };
      return this.swf.PollForActivityTask(swfCfg, function(err, data) {
        var body, task, token;
        if (err != null) {
          return process.nextTick(function() {
            return _this.workerFn(err, null);
          });
        } else {
          body = data.Body;
          token = body.taskToken;
          inspect(data);
          if (!(token != null)) {
            console.log("No activity task in the pipe, repolling...");
            return process.nextTick(function() {
              return _this.poll();
            });
          } else {
            console.log("New task received");
            task = new ActivityTask(_this.swf, body);
            return process.nextTick(function() {
              _this.workerFn(null, task);
              return _this.poll();
            });
          }
        }
      });
    };

    return Activity;

  })();

  exports.Activity = Activity;

}).call(this);
