// Generated by CoffeeScript 1.3.3
(function() {
  var ActivityTask, inspect;

  inspect = require('eyes').inspector();

  ActivityTask = (function() {

    function ActivityTask(swf, task) {
      this.swf = swf;
      this.task = task;
    }

    ActivityTask.prototype.respondCompleted = function(result, callBack) {
      var cBack, swfCfg;
      if (typeof result !== "string") {
        result = JSON.stringify(result);
      }
      swfCfg = {
        "TaskToken": this.task.taskToken,
        "Result": result
      };
      cBack = callBack != null ? callBack : function(err) {
        if (err != null) {
          return console.log("Error executing: respondCompleted");
        }
      };
      return this.swf.RespondActivityTaskCompleted(swfCfg, cBack);
    };

    return ActivityTask;

  })();

  exports.ActivityTask = ActivityTask;

}).call(this);
