// Generated by CoffeeScript 1.3.3
(function() {
  var ActivityResponse, inspect;

  inspect = require('eyes').inspector();

  ActivityResponse = (function() {

    function ActivityResponse(app, name, token) {
      var i;
      this.app = app;
      this.token = token;
      for (i in this.app.activities) {
        if (this.app.activities[i].name === name) {
          this.swf = this.app.activities[i].swfClient;
        }
      }
    }

    ActivityResponse.prototype.send = function(result, cBack) {
      var swfCfg;
      if (typeof result !== "string") {
        result = JSON.stringify(result);
      }
      swfCfg = {
        "TaskToken": this.token,
        "Result": result
      };
      cBack = typeof callBack !== "undefined" && callBack !== null ? callBack : function(err) {
        if (err != null) {
          return this.pp.logger.error("Error sending activity response", err);
        }
      };
      return this.swf.RespondActivityTaskCompleted(swfCfg, cBack);
    };

    return ActivityResponse;

  })();

  exports.ActivityResponse = ActivityResponse;

}).call(this);
