// Generated by CoffeeScript 1.3.3
(function() {
  var DecisionTask, inspect,
    __slice = [].slice;

  inspect = require('eyes').inspector();

  DecisionTask = (function() {

    function DecisionTask(swf, task) {
      this.swf = swf;
      this.task = task;
    }

    DecisionTask.prototype.respondCompleted = function(decisions, callBack) {
      var swfCfg,
        _this = this;
      swfCfg = {
        "TaskToken": this.task.taskToken,
        "Decisions": decisions
      };
      return this.swf.RespondDecisionTaskCompleted(swfCfg, function(err, data) {
        if (callBack != null) {
          return process.nextTick(function() {
            return callBack(err, data);
          });
        } else {
          if (err != null) {
            console.log("Error executing: respondCompleted");
          }
          if (data != null) {
            return console.log("Successfully executed: respondCompleted");
          }
        }
      });
    };

    DecisionTask.prototype.completeWorkflowExecution = function(callBack) {
      var decisions;
      decisions = [
        {
          "decisionType": "CompleteWorkflowExecution",
          "completeWorkflowExecutionDecisionAttributes": {
            "result": "Finished !"
          }
        }
      ];
      return this.respondCompleted(decisions, callBack);
    };

    DecisionTask.prototype.failWorkflowExecution = function() {
      var cBack, callBack, decisions, details, reason, _i, _ref;
      reason = arguments[0], details = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callBack = arguments[_i++];
      decisions = [
        {
          "decisionType": "FailWorkflowExecution",
          "failWorkflowExecutionDecisionAttributes": {
            "reason": reason,
            "details": (_ref = details[0]) != null ? _ref : "none provided by the user"
          }
        }
      ];
      cBack = callBack != null ? callBack : function(err) {
        if (err != null) {
          return console.log("Error executing: failWorkflowExecution");
        }
      };
      return this.respondCompleted(decisions, cBack);
    };

    DecisionTask.prototype.scheduleActivityTask = function() {
      var activityName, cBack, callBack, decisions, input, _i, _ref;
      activityName = arguments[0], input = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callBack = arguments[_i++];
      decisions = [
        {
          "decisionType": "ScheduleActivityTask",
          "scheduleActivityTaskDecisionAttributes": {
            "activityId": activityName + "-" + ((Math.random() + "").substr(2)),
            "activityType": {
              "name": activityName,
              "version": "1.0"
            },
            "input": (_ref = input[0]) != null ? _ref : 'none',
            "taskList": {
              "name": activityName + "-default-tasklist"
            }
          }
        }
      ];
      inspect(decisions);
      cBack = callBack != null ? callBack : function(err) {
        if (err != null) {
          return console.log("Error executing: scheduleActivityTask");
        }
      };
      return this.respondCompleted(decisions, cBack);
    };

    return DecisionTask;

  })();

  exports.DecisionTask = DecisionTask;

}).call(this);
