// Generated by CoffeeScript 1.3.3
(function() {

  exports.checkDomain = function(swf, domainName, force, callBack) {
    var swfParams,
      _this = this;
    if (force == null) {
      force = false;
    }
    swfParams = {
      Name: domainName
    };
    return swf.DescribeDomain(swfParams, function(descDomainErr, descDomainData) {
      if (descDomainErr != null) {
        if ((descDomainErr.Body != null) && (descDomainErr.Body.__type != null) && descDomainErr.Body.__type.indexOf("UnknownResourceFault") > -1) {
          if (!force) {
            return callBack({
              err: "NO_DOMAIN",
              message: "Domain " + domainName + " doesnt exist. Please use the force option to create it."
            });
          } else {
            swfParams = {
              'Name': domainName,
              'WorkflowExecutionRetentionPeriodInDays': '1'
            };
            return swf.RegisterDomain(swfParams, function(regDomainErr, regDomainData) {
              if (regDomainErr != null) {
                return callBack({
                  err: "UNEXPECTED",
                  message: "Unexpected error encountered",
                  context: regDomainErr
                });
              } else {
                return callBack(null, domainName);
              }
            });
          }
        } else {
          return callBack({
            err: "UNEXPECTED",
            message: "Unexpected error encountered",
            context: descDomainErr
          });
        }
      } else {
        return callBack(null, domainName);
      }
    });
  };

  exports.checkWorkflow = function(swf, domainName, workflowName, taskList, force, callBack) {
    var swfParams,
      _this = this;
    if (force == null) {
      force = false;
    }
    swfParams = {
      Domain: domainName,
      WorkflowType: {
        name: workflowName,
        version: "1.0"
      }
    };
    return swf.DescribeWorkflowType(swfParams, function(descWflErr, descWflData) {
      if (descWflErr != null) {
        if ((descWflErr.Body != null) && (descWflErr.Body.__type != null) && descWflErr.Body.__type.indexOf("UnknownResourceFault") > -1) {
          if (!force) {
            return callBack({
              err: "NO_WORKFLOW",
              message: "Workflow " + domainName + "/" + workflowName + " doesnt exist. Please use the force option to create it."
            });
          } else {
            swfParams = {
              "Domain": domainName,
              "Name": workflowName,
              "Version": "1.0",
              "Description": "Automatically created workflow type.",
              "DefaultTaskStartToCloseTimeout": "600",
              "DefaultExecutionStartToCloseTimeout": "3600",
              "DefaultTaskList": {
                "name": "" + taskList
              },
              "DefaultChildPolicy": "TERMINATE"
            };
            return swf.RegisterWorkflowType(swfParams, function(regWflErr, regWflData) {
              if (regWflErr != null) {
                return callBack({
                  err: "UNEXPECTED",
                  message: "Unexpected error encountered",
                  context: regWflErr
                });
              } else {
                return callBack(null, workflowName);
              }
            });
          }
        } else {
          return callBack({
            err: "UNEXPECTED",
            message: "Unexpected error encountered",
            context: descWflErr
          });
        }
      } else {
        return callBack(null, workflowName);
      }
    });
  };

  exports.checkActivity = function(swf, domainName, activityName, taskList, force, callBack) {
    var swfParams,
      _this = this;
    if (force == null) {
      force = false;
    }
    swfParams = {
      Domain: domainName,
      ActivityType: {
        name: activityName,
        version: "1.0"
      }
    };
    return swf.DescribeActivityType(swfParams, function(descActErr, descActData) {
      if (descActErr != null) {
        if ((descActErr.Body != null) && (descActErr.Body.__type != null) && descActErr.Body.__type.indexOf("UnknownResourceFault") > -1) {
          if (!force) {
            return callBack({
              err: "NO_ACTIVITY",
              message: "Activity " + domainName + "/" + activityName + " doesnt exist. Please use the force option to create it."
            });
          } else {
            swfParams = {
              "Domain": domainName,
              "Name": activityName,
              "Version": "1.0",
              "Description": "Automatically created activity type",
              "DefaultTaskStartToCloseTimeout": "600",
              "DefaultTaskHeartbeatTimeout": "120",
              "DefaultTaskList": {
                "name": taskList
              },
              "DefaultTaskScheduleToStartTimeout": "300",
              "DefaultTaskScheduleToCloseTimeout": "900"
            };
            return swf.RegisterActivityType(swfParams, function(regActErr, regActData) {
              if (regActErr != null) {
                return callBack({
                  err: "UNEXPECTED",
                  message: "Unexpected error encountered",
                  context: regActErr
                });
              } else {
                return callBack(null, activityName);
              }
            });
          }
        } else {
          return callBack({
            err: "UNEXPECTED",
            message: "Unexpected error encountered",
            context: descActErr
          });
        }
      } else {
        return callBack(null, activityName);
      }
    });
  };

}).call(this);
